### ISSUE TITLE
Cache Not Found while cache key are the same

### ISSUE THREAD

**Issue by linonetwo** [Swatinem/rust-cache#119]
![截屏2023-02-16 13 38 29](https://user-images.githubusercontent.com/3746270/219278315-ff0bcbdb-1716-4f5b-aec1-b993fde12be2.png)

save in https://github.com/toeverything/AFFiNE/actions/runs/4190695664/jobs/7264363757

![截屏2023-02-16 13 39 05](https://user-images.githubusercontent.com/3746270/219278322-a4875a94-5d63-45d3-b245-bb5e6e69361d.png)

load in [https://github.com/toeverything/AFFiNE/actions/runs/4191029560/jobs/7265049867](https://github.com/toeverything/AFFiNE/actions/runs/4191029560/jobs/7265049867)

Folder  structure is 

![](https://user-images.githubusercontent.com/3746270/219278519-bb2f01b0-636f-4ebe-bc27-6bb9a8a5842b.png)

And the script is [https://github.com/toeverything/AFFiNE/blob/520076b31df9253f12e8271a34ef8cf50f11164a/.github/workflows/client-app.yml#L98-L103](https://github.com/toeverything/AFFiNE/blob/520076b31df9253f12e8271a34ef8cf50f11164a/.github/workflows/client-app.yml#L98-L103)

```
      - name: Get rust cache
        uses: Swatinem/rust-cache@v2
        id: rust-cache
        with:
          workspaces: |
            apps/desktop/src-tauri
```
