### ISSUE TITLE
Support for working-directory in v2 action for monorepos

### ISSUE THREAD

**Issue by sazzer** [Swatinem/rust-cache#133]
I've been using the v1 of this action for a while now, and it's worked great. I've just noticed that there's a v2 however, and this isn't working for me.

I've got a monorepo setup whereby I've got a Rust backend and a JS frontend in the same repo. As such, the Rust repo is not in the root of the repo but in a subdirectory.

My old config was this:
```
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: service
          cache-on-failure: true
```

But as soon as I change this to v2 I'm told that `working-directory` is not supported. Are there any plans to bring this back?

Cheers
