### ISSUE TITLE
Nightly pinning

### ISSUE THREAD

**Issue by DrewRidley** [Swatinem/rust-cache#148]
Hi!

If we use nightly with this action, but pin to a specific nightly release, will the cache work accordingly?
Thanks for your help

**Comment by Swatinem** [comment]
It should, yes. It basically uses the output of `rustc -vV` to create its own hash:

https://github.com/Swatinem/rust-cache/blob/988c164c3d0e93c4dbab36aaf5bbeb77425b2894/src/config.ts#L84-L86

So if you pin the nightly release, the commit-hash in particular should be stable.

**Comment by DrewRidley** [comment]
Currently we have a toolchain file like so:

```toml
[toolchain]
#Pinned so that CI/CD is able to cache toolchain version.
channel = "nightly-2023-06-16"
```

Prior to using nightly, we saw each build would only build the project crates, and no dependencies. Despite the output of your script saying it did indeed pull from the cache, it ends up building hundreds of dependencies every build. Is there any reason this doesn't work as well as we hoped?
