### ISSUE TITLE
Cargo `mtime` issue preventing effective caching on `git` dependencies

### ISSUE THREAD

**Issue by 0o-de-lally** [Swatinem/rust-cache#155]
Hi all I work on a few repos with hundreds of external dependencies at the root level. Many of those are specified as `git` paths. @Swatinem pointed out this issue to me related to `mtimes`.

TL;DR: The cargo caching of GitHub dependencies has a known issue with being cached by timestamp, and not hash. https://github.com/rust-lang/cargo/issues/6529

It's not as simple as saving `~/.cargo/git/checkouts` since the timestamp gets updated. See this message for what seems to be happening: the cargo git dependencies appear to be more recent than the checked out code.
https://github.com/rust-lang/cargo/issues/6529#issuecomment-1558380049

The solutions are more convoluted. A number of people have workarounds:
https://github.com/rust-lang/cargo/issues/6529#issuecomment-1558438048

There's a clue in a recently linked github issue. It may be possible to leverage an existing mtime resetting github action. I'm looking at that currently.
https://github.com/paradigmxyz/reth/commit/a22c274394da913b327ad1bfdb2db008b272f0ab

**Comment by tmm1** [comment]
Thanks for this summary!

I was noticing a lot of rebuilds, and adding `CARGO_TERM_VERBOSE=true` showed "Dirty" entries like:

```
       Fresh pin-project v1.1.10
       Dirty myfs v0.4.23 (./ignore): the file `myfs/src/lib.rs` has changed (1750913404.153891863s, 17m 57s after last build at 1750912327.777027781s)
   Compiling myfs v0.4.23 (./myfs)

```

This led me to the `retimer` solution mentioned on one of the linked threads, which I recreated [here](https://gist.github.com/tmm1/0ec42a8a12bf78ece7a43ec6204cbdc3). I'm using this as so:

```yml
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-workspace-crates: true
          cache-directories: |
            ${{ github.workspace }}/.retimer-state
          workspaces: |
            . -> target

      - name: npm build for rust
        run: |
          ./retimer.sh restore
          cargo build
          ./retimer.sh save
        env:
          CARGO_TERM_VERBOSE: true
```

However, I still observe the final project is always rebuilt (90s+ in my case), even if none of the code has changed.

```
       Dirty myproj v0.0.0 (/home/runner/_work/myorg/myrepo/myproj): stale, unknown reason
```
