### ISSUE TITLE
Fails to handle cache key consisting of command line flags.

### ISSUE THREAD

**Issue by VorpalBlade** [Swatinem/rust-cache#157]
It seems rust-cache fails to handle this fragment (from https://github.com/VorpalBlade/chezmoi_modify_manager):

```yaml
  configurations:
    # Test non-standard configurations, MSRV and Rust versions
    name: Test - "${{ matrix.features }}" on Linux with Rust ${{ matrix.rust }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - --no-default-features
          - --no-default-features --features=updater-tls-native
          - --no-default-features --features=updater-tls-native-vendored
          - --no-default-features --features=updater-tls-rusttls
        rust:
          - 1.69.0
          - stable
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup install --profile minimal  ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Cache builds
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.features }}
      - name: Compile and test
        run: cargo test --locked ${{ matrix.features }} --verbose
```

Specifically, using `${{ matrix.features }}` as a cache key doesn't seem to work here, no caches are ever created for this block. Caches work for other blocks where the key is things like `matrix.target` (host triplets for cross compiling).
