### ISSUE TITLE
Target directory cleaned even though cache-targets: true

### ISSUE THREAD

**Issue by fooblahblah** [Swatinem/rust-cache#171]
I'm probably doing something wrong, but it appears when `cache-targets: true` is specified and I'm running from an empty cache state, I see a cleaning step before the save of `target`. This ends up failing the subsequent run(s) which depend on the target dir to be cached with the generated binaries.

My cargo-cache action is as follows:
```
      - id: cargo-cache
        name: cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ci-${{ runner.os }}
          cache-targets: true
```

However, when the cache is in the post build cache phase I see the following:
![image](https://github.com/Swatinem/rust-cache/assets/130910/9219bb74-37b7-4397-9cfa-190e133ff45b)

Is there any workaround I can try like specifying the target dir in the keys?
