### ISSUE TITLE
Consider `CARGO_TARGET_DIR` env variable

### ISSUE THREAD

**Issue by phil-opp** [Swatinem/rust-cache#173]
The [`CARGO_TARGET_DIR` env variable](https://doc.rust-lang.org/cargo/reference/environment-variables.html) can be set to override the directory where `cargo` should place the compilation artifacts (i.e. the `target` folder).

Setting this env variable can be useful on CI to work around disk space limitations. For example, the GitHub actions Windows CI runners have more disk space available on `C:` than `D:`, so you can move the `target` folder to the `C:` drive to avoid disk space errors on larger projects.

Unfortunately, the `rust-cache` action does not consider the `CARGO_TARGET_DIR` env variable and continues to cache a local `target` directory, which is now empty.

**Comment by phil-opp** [comment]
The workaround is quite simple fortunately:

```yaml
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ${{ env.CARGO_TARGET_DIR }}
```
