### ISSUE TITLE
Am I using it correctly?

### ISSUE THREAD

**Issue by TheGP** [Swatinem/rust-cache#224]
It seems it doesn't work:

```
name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # Disable incremental compilation for faster from-scratch builds

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2.7.7

    - name: Build
      run: cargo build --release
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL_LOCAL }}
```
