### ISSUE TITLE
Cache restore failing on codebuild self-hosted runner

### ISSUE THREAD

**Issue by gtrak** [Swatinem/rust-cache#229]
I'm using rust-cache via setup-rust-toolchain.

A cache is getting saved, but it's not getting restored when rerunning on a PR branch, and I think the paths might be responsible. They seem to be relative on the write-side, but on the read side include randomly generated numbers.  Am I on the right track? 

restore side:

![Image](https://github.com/user-attachments/assets/fba73582-95af-44ea-b8dc-4287b04dc37c)

![Image](https://github.com/user-attachments/assets/5090eaa5-84a4-40ae-b62b-59651ede9f7a)

write side:
```
##[debug]Cache Paths: 
##[debug]["../../../../../../../../root/.cargo/bin","../../../../../../../../root/.cargo/registry","workspace-path/target"]
```

![Image](https://github.com/user-attachments/assets/69e79aba-1507-4cac-81ae-814eafa86e43)

workflow snippet:
```
jobs:
  test-and-build:
    runs-on: codebuild-gha-runner-${{ github.run_id }}-${{ github.run_attempt }}
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: |
            workspace-path -> target
      - name: Run tests
        run: |
          cd workspace-path
          cargo test
```
