### ISSUE TITLE
way to always use latest cache if there is no cache key match?

### ISSUE THREAD

**Issue by sam0x17** [Swatinem/rust-cache#230]
Our project is based on substrate which is a 425+ crate workspace so there is a massive amount of cachiness, even when there is no cache hit, it would always be useful to load whatever has been recently added to the cache. Is there some way to either completely override the cache key to not be based on git changes, or otherwise specify that it should just pull the latest cache entry when there is a cache miss? That would be ideal for us

**Comment by masterzorgon** [comment]
> Our project is based on substrate which is a 425+ crate workspace so there is a massive amount of cachiness, even when there is no cache hit, it would always be useful to load whatever has been recently added to the cache. Is there some way to either completely override the cache key to not be based on git changes, or otherwise specify that it should just pull the latest cache entry when there is a cache miss? That would be ideal for us

I agree. Merge!!!!!

**Comment by abdulrabbani00** [comment]
Just checked some things and it seems like this can't be fixed in the codebase. [This is a limitation of Github](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache). They don't allow caches to be shared across branches, but you can access the cache from the base branch.

What I am going to do and recommend is that you save a cache on merge and then all your PR's can fallback to that cache.

```
name: Rust Cache Maintenance

on:
  push:
    branches:
      - main
    paths:
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - 'rust-toolchain.toml'

jobs:
  update-cache:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Update Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "v0"
          shared-key: "shared"
          # Force save the cache even if no dependencies changed
          save-if: "true"
          # Cache on failure to preserve the state
          cache-on-failure: true
          
      # This step ensures all dependencies are downloaded and compiled
      # which updates the cache with the latest state
      - name: Build all targets
        run: cargo build --all-targets 
```
