### ISSUE TITLE
What am I doing wrong

### ISSUE THREAD

**Issue by exokernel** [Swatinem/rust-cache#232]
I can't get this to work for the life of me

```
name: Create Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 # Disable incremental compilation for faster from-scratch builds

jobs:
  build:
    name: Build and Release
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # I can't get this to work
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.7

      - name: Build Release Binary
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/release/rssh
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

With this workflow file I am getting cache misses every time. Even when tagging the same commit. No changes to the repo.
