### ISSUE TITLE
cross targetting support

### ISSUE THREAD

**Issue by youknowone** [Swatinem/rust-cache#33]
I wrote workflow setup like:
```yaml
      - uses: actions-rs/toolchain@v1
        with:
          target: i686-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v1
```

But it seems it doesn't work for cross target.

When looking for cache:
```
    v0-rust-exotic_targets-1.55.0-x86_64-unknown-linux-gnu-c8dfcfe046a7
No cache found.
```

When trying cache:
```
Warning:  Unable to locate executable file: rustc. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```
