### ISSUE TITLE
cargo test SIGILL - not sure if this is related

### ISSUE THREAD

**Issue by keepsimple1** [Swatinem/rust-cache#36]
I am using `rust-cache` in my GitHub Actions with default options, like this:

```
      - name: Checkout
         uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Cargo actions.
      - name: Run rustfmt and fail if any warnings
        run: cargo fmt -- --check
      - name: Build
        run: cargo build --color=always
      - name: Run clippy and fail if any warnings
        run: cargo clippy -- -D warnings
      - name: Run tests
        run: cargo test
```

Sometimes,  `cargo build` or `cargo test` would crash due to an error like this: 
```
Caused by:
  process didn't exit successfully: `<my_path>/target/debug/deps/integration_tests-a0b2fd9edc2b1e73` (signal: 4, SIGILL: illegal instruction)
```

If I remove the use of `rust-cache` and re-run Actions, it would succeed.  This happened with or without Cargo.toml changes.

Is there any known issue that could cause SIGILL during cargo build or cargo test?
