### ISSUE TITLE
Add support for the `cache-hit` output

### ISSUE THREAD

**Issue by austinjones** [Swatinem/rust-cache#5]
The `actions/cache@v2` plugin supports an output variable called `cache-hit`, which is set to true if there is an exact match.  This is really useful for conditional steps later in the job, such as a `cargo build` call:

```
      - name: cargo build | dependencies
        uses: actions-rs/cargo@v1
        if: steps.cargo-cache.outputs.cache-hit != 'true'
        with:
          command: build
```

This would be a great output variable for `rust-cache`, and would make it a drop-in replacement for `actions/cache@v2`.
