### ISSUE TITLE
Doesn't cache across multiple PRs

### ISSUE THREAD

**Issue by mercxry** [Swatinem/rust-cache#61]
Hey,

I set up rust-cache with a `sharedKey` and it works when re-doing the same jobs on the same PR, but when I'm doing the same job on another PR the cache doesn't retrieve anything even if the caching key it's the same.

I have also noticed that the cache seems to not get persisted in the "Storage for Actions" because in my account billing that field it's 0.0GB out of 2.0GB, while the action logs output a cache of 444MB.

I'm not sure what I'm doing wrong or if this is by design, but this is my configuration for the CI:
```
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v1
        with:
          sharedKey: cache-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true
```

Thanks for building this tool, would be super useful if I can overcome this issue 😄
