### ISSUE TITLE
`cargo install`s not cached on linux

### ISSUE THREAD

**Issue by AntoniosBarotsis** [Swatinem/rust-cache#86]
I'm not sure if I'm doing something wrong but it seems that `cargo install`s are only cached on windows and mac.

I run `cargo install hyperfine` as part of my workflow which consistently takes 1 minute on linux while it only takes 1-2 seconds on mac and windows.

Here's a rough outline of the workflow

```yml
  build_test_run:
    name: Build and test on ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: aarch64-unknown-linux-gnu , os: ubuntu-22.04 }
          - { target: x86_64-unknown-linux-gnu  , os: ubuntu-22.04 }
          - { target: x86_64-apple-darwin       , os: macos-12     }
          - { target: x86_64-pc-windows-msvc    , os: windows-2022 }
[...]

      - name: Use cached dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: "${{ matrix.job.os }}-${{ matrix.job.target }}-${{ hashFiles('**/Cargo.lock') }}"
          shared-key: "shared"

[...]

      - name: Install Hyperfine
        run: cargo install hyperfine
```

I tried doing `cargo install --path target` but that seemed to have the same result (which makes sense since the action seems to be checking both `target` and `~/.cargo/`.

What's interesting is that the project itself seems to be cached properly as the build times are very much comparable across the 3 platforms.

The full workflow can be found [here](https://github.com/AntoniosBarotsis/Rss2Email/blob/8162aa19a4dd38b67d2fd8d5cd3a2f76589c0012/.github/workflows/ci.yml#L66-L109) and a workflow run can be inspected [here](https://github.com/AntoniosBarotsis/Rss2Email/actions/runs/3311815368).
