### ISSUE TITLE
Irrelivent Cargo.toml and Cargo.lock files being considered for cache key

### ISSUE THREAD

**Issue by adam-azarchs** [Swatinem/rust-cache#89]
In a large mono-repo with multiple cargo workspaces, we have separate github actions for testing each one, using e.g.
```yaml
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: lib/rust1
```
However looking at the output from the post-build action, it's considering the `Cargo.toml` and `Cargo.lock` files from other workspaces, when it clearly shouldn't be.

It also isn't excluding `Cargo.toml` files from directories which have been explicitly excluded from the workspace.  I understand that's maybe harder to deal with than avoiding crates which are outside of the workspace path, but if you're parsing the cargo metadata one should be able to get the complete set of `Cargo.toml` files which actually matter for the workspace.
