### ISSUE TITLE
Failed to use the cache from base branch

### ISSUE THREAD

**Issue by AurelienFT** [Swatinem/rust-cache#98]
Hello,

I have simple CI job that use rust-cache

```yml
 sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2022-12-24
          components: rustfmt
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "sanity"
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
```

I want that job to be able to reuse the dependencies from the base branch but when I look at the output it says that it didn't found any cache for the key. When I go on the `Cache` section after the job finish I have this:

<img width="1048" alt="Screenshot 2022-12-29 at 12 10 11" src="https://user-images.githubusercontent.com/32803821/209965827-78b7bf54-7933-4c19-bec9-baff8d0745aa.png">

3280 is the base branch of 3354 so I don't understand why the CI made a new cache on the 3354 and didn't found the cache on the 3280 as they have the same key and 3280 is the base. I have read the documentation on GitHub Cache that says : 

> For example, if the branch feature-b has the base branch feature-a, a workflow run triggered on a pull request would have access to caches created in the default main branch, the base feature-a branch, and the current feature-b branch.

[Link](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)

EDIT: The fact that I have multiple caches is a problem because it make my max of 10 GB explode.

I'm missing a config parameter ? Or do you have any advice on how I could make the branch based on 3280 use his cache ?
