### ISSUE TITLE
Using cache with `--manifest-path=<path>/Cargo.toml`

### ISSUE THREAD

**Issue by rherrmannr** [Swatinem/rust-cache#99]
I'm struggling to get `rust-cache` running using an `action.yml` combined with a specific `manifest-path`.

I have the following `action.yml`:
```
  steps:
  - uses: actions/checkout@v3
  - uses: dtolnay/rust-toolchain@stable
  - name: Install Cargo Lambda
    uses: jaxxstorm/action-install-gh-release@v1.9.0
    with:
      repo: cargo-lambda/cargo-lambda
      tag: v0.14.0
      platform: linux
      arch: x86_64
  - uses: goto-bus-stop/setup-zig@v2
  - uses: Swatinem/rust-cache@v2
    with:
      workspaces: "topics/registry/target/"
  - name: Release Build
    shell: bash
    run: cargo lambda build --release --output-format=zip --manifest-path=topics/registry/Cargo.toml
```

As you can see, the `Cargo.toml` is based on `topics/registry/`. The build is successful, artefacts will be uploaded and I get notified that the cache is being restored:

```
/usr/bin/tar --use-compress-program unzstd -xf /home/runner/work/_temp/2b1e05d0-7f9e-4da2-9462-014cb2c040b4/cache.tzst -P -C /home/runner/work/backend/backend
Cache restored successfully
Restored from cache key "v0-rust-build-7fdeeb023f5033af4df121a9712269ffa02d3105-da39a3ee5e6b4b0d3255bfef95601890afd80709".
```

The `action.yml` is called from a top-level workflow in `.github/workflows/build.yml` with `- uses: ./topics/registry/`.

I've tried to use the `workspace` and specify it accordingly to `"topics/registry/target/"`, but it has no effect. Every dependency will be built once again.

Can someone help me specify rust-cache correctly, please? It worked for me once when the rust part was on a top level when a `manifest-path` and `workspace` was not required.

The repo is public: https://github.com/rust-iot-things/backend/actions/runs/3802529509/jobs/6468103117#step:3:260
